linreg<-setRefClass("linreg",fields=list(formula='formula',data='data.frame',reg_coe='matrix',fitted_value='matrix',residuals='matrix',df='numeric',res_var='matrix',var_reg_coe='matrix'),methods=list(
  initialize = function(formula,data){
    formula<<-formula
    data<<-data
    calculate_Regressions_coefficients()
    calculate_the_fitted_value()
    calculate_the_residuals()
    calculate_degress_of_freedom()
    calculate_residual_variance()
    calculate_var_reg_coe()
  },
  calculate_Regressions_coefficients=function(){
    x<-get_matrix_x()
    y<-get_matrix_y()
    reg_coe<<-solve((t(x)%*%x))%*%t(x)%*%y
  },
  calculate_the_fitted_value=function(){
    fitted_value<<-get_matrix_x()%*%reg_coe
  },
  calculate_the_residuals=function(){
    residuals<<-get_matrix_y()-fitted_value
  },
  get_matrix_y=function(){
    #formula<-formula(formula)
    y_name<-all.vars(formula)[1]
    y<-data[y_name]
    return (as.matrix(y))
  },
  calculate_degress_of_freedom=function(){
    x<-get_matrix_x()
    df<<-nrow(x)-ncol(x)
  },
  get_matrix_x=function(){
    fm<-formula(formula)
    fm<-lm(fm,data)
    x<-model.matrix(fm)
    # delete intercept
    return (as.matrix(x))
    #print(x[,-1])
  },
  calculate_residual_variance=function(){
    #return(print(df))
    res_var<<-(t(residuals)%*%residuals)/df
  },
  calculate_var_reg_coe=function(){
    x<-get_matrix_x()
    var_reg_coe<<-res_var[1,1]*solve((t(x)%*%x))
  },
  calculate_t_value=function(){
    t_value<-reg_coe/sqrt(diag(var_reg_coe))
    #t_value<-reg_coe/sqrt(var(reg_coe))
    return(t_value)
    
    #return(sqrt(var(reg_coe)))
  },
  print=function(){
    str<-cat("Coefficients:\n")
    v<-c(str,reg_coe[,1])
    return(v)
  },
  plot=function(){
    qplot(x=fitted_value,y=residuals)
  }
))
#l1<-linreg$new(formula=Sepal.Length~Sepal.Width+Petal.Length,data=iris)
# create instance using class
d<-lm(formula=Petal.Length~Species,data=iris)
summary(d)
library(ggplot2)
l1<-linreg$new(formula=Petal.Length~Species,data=iris)
l1$plot()
l1$calculate_t_value()